# Generated by Django 4.2.6 on 2023-10-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('top', 'Top Priority'), ('middle', 'Middle Priority'), ('low', 'Less Priority')], default='top', max_length=10)),
                ('deadline', models.DateField()),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
